# Generated by Django 4.0.4 on 2022-04-19 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='email_allow',
            field=models.BooleanField(default=False, verbose_name='이메일수신여부'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='sms_allow',
            field=models.BooleanField(default=False, verbose_name='문자수신여부'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='emailAddress',
            field=models.EmailField(max_length=254, verbose_name='이메일주소'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phonenumber',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
