# Generated by Django 4.0.4 on 2022-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_faq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='answerstate',
            field=models.CharField(choices=[('ER', '문의등록'), ('RP', '접수완료'), ('RC', '답변완료')], default='ER', max_length=2, verbose_name='상태'),
        ),
    ]
